name: hyp3-rtc-gamma
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.7
  - pip
  # For packaging, and testing
  - pytest
  - pytest-console-scripts
  - pytest-cov
  - setuptools
  - setuptools_scm
  - wheel
  # For running
  - boto3
  - hyp3lib>=1.5.0,<2
  - importlib_metadata
  - numpy
  - pillow
  - scipy
  - pip:
    # for packaging and testing
    - s3pypi
    - safety
    # For running
    - --trusted-host hyp3-pypi.s3-website-us-east-1.amazonaws.com
      --extra-index-url http://hyp3-pypi.s3-website-us-east-1.amazonaws.com
    - hyp3proclib>=1.0.1,<2
