name: hyp3-gamma
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.7
  - pip
  # For packaging, and testing
  - flake8
  - flake8-import-order
  - flake8-blind-except
  - flake8-builtins
  - setuptools
  - setuptools_scm
  - wheel
  - pytest
  - pytest-console-scripts
  - pytest-cov
  # For running
  - hyp3lib>=1.6.0,<2
  - importlib_metadata
  - numpy
  - pip:
    # for packaging and testing
    - s3pypi
    - safety
    # For running
    - --trusted-host hyp3-pypi.s3-website-us-east-1.amazonaws.com
      --extra-index-url http://hyp3-pypi.s3-website-us-east-1.amazonaws.com
    - hyp3_metadata>=0.1.2,<1
