name: hyp3-gamma
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.8
  - pip
  # For packaging, and testing
  - flake8
  - flake8-import-order
  - flake8-blind-except
  - flake8-builtins
  - setuptools
  - setuptools_scm
  - wheel
  - pytest
  - pytest-console-scripts
  - pytest-cov
  # For running
  - gdal
  - geopandas
  - hyp3lib>=1.7.0,<2
  - importlib_metadata
  - jinja2
  - lxml
  - numpy>=1.17,<1.18
  - pillow
  - python-dateutil
