name: Write release and finish

on:
  push:
    tags:
      - v*


jobs:
  finish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.TOOLS_BOT_PAK }}

      - name: Create Release
        uses: docker://antonyurchenko/git-release:v3.5.0
        env:
          GITHUB_TOKEN: ${{ secrets.TOOLS_BOT_PAK }}
          RELEASE_NAME_PREFIX: "HyP3 GAMMA "
          ALLOW_TAG_PREFIX: true

      - name: Attempt fast-forward develop from master
        run: |
          git fetch --prune
          git checkout develop && git pull --ff-only
          git merge --ff-only origin/master
          git push

      - name: Open PR to bring master back to develop
        if: ${{ failure() }}
        uses: repo-sync/pull-request@v2
        with:
          source_branch: master
          destination_branch: develop
          pr_title: Pulling ${{ github.ref }} into default
          pr_body: Fast-forward of master to default failed!
          pr_assignee: ${{ github.actor }}
          pr_label: tools-bot
          pr_draft: false
          pr_allow_empty: true
          github_token: ${{ secrets.TOOLS_BOT_PAK }}
