name: Write release and finish

on:
  push:
    tags:
      - 'v*'

jobs:
  call-release-workflow:
    uses: ASFHyP3/actions/.github/workflows/reusable-release.yml@main
    with:
      release_prefix: HyP3 GAMMA
    secrets:
      USER_TOKEN: ${{ secrets.TOOLS_BOT_PAK }}
